### PR TITLE
Add support for es2015 field

### PR DESCRIPTION
**Pull request by gregmagolan**
The `es2015` package.json field is part of both angular and rxjs npm packages. Default is set to false so as not to change the current behavior.

For reference, https://www.npmjs.com/package/rollup-plugin-node-resolve-angular and https://www.npmjs.com/package/rollup-plugin-node-resolve-next both handle the `es2015` field.

### CODE REVIEW

**Comment by gregmagolan** [comment]
This change would be helpful downstream in https://github.com/bazelbuild/rules_nodejs/pull/429 and https://github.com/angular/angular/pull/27220.

**Comment by TrySound** [comment]
Better to achieve this via https://github.com/rollup/rollup-plugin-node-resolve/pull/182

**Comment by gregmagolan** [comment]
@TrySound Can we land this in the meantime since #182 is stalled? This is a small change relative to #182.

**Comment by TrySound** [comment]
It's not stalled. Maintainers don't have free time to finish it. And we wouldn't like to add a feature which will be removed later.

**Pull request closed without merging**
