### PR TITLE
replace buble with babel, update deps

### PR DESCRIPTION
**Pull request by mecurc**
This PR is a part of changesets described here https://github.com/rollup/rollup-plugin-node-resolve/pull/213#issuecomment-489497514

### CODE REVIEW

**Comment by mecurc** [comment]
Should I create another PR where I update dependencies?

**Comment by lukastaegert** [comment]
> Can I update those inside this PR?

Definitely!

**Comment by mecurc** [comment]
After those changes, I think we can rewrite sources to async-await syntax. It will be compiled to promises by babel then we just change target version to 8 ;)

I already have a branch with refactored this package to async-await syntax. Should I send a PR?

**Comment by lukastaegert** [comment]
Sounds good! I assume it will also work for the tests via babel-register?

**Comment by mecurc** [comment]
> Sounds good! I assume it will also work for the tests via babel-register?

I think yes. It already works with it.

current mocha opts:
```
--require @babel/register
```

**Comment by mecurc** [comment]
SHould I add refactored to async-await version to this PR?

**Comment by lukastaegert** [comment]
> SHould I add refactored to async-await version to this PR?

Sure, sounds good, considering you already seem to have done the work. Just avoid `utils/promisify` for the Node 6 compatibility.

**Comment by mecurc** [comment]
I prefer to merge this PR as is. Then I add PR with refactored to async-await syntax.

**Pull request merged**
