### PR TITLE
fix: add guard for options.browser with no pkg.browser field

### PR DESCRIPTION
**Pull request by keithamus**
This adds a fix for the problem described in https://github.com/rollup/rollup-plugin-node-resolve/pull/127#issuecomment-356690466

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Thanks, released 3.0.2 👍

**Comment by Haroenv** [comment]
Perfect!

**Comment by wKovacs64** [comment]
@keithamus Hmm, this broke my build. I get this as of 3.0.2:

```shell
[!] Error: Unexpected token
node_modules/axios/package.json (2:8)
1: {
2:   "name": "axios",
           ^
3:   "version": "0.17.1",
4:   "description": "Promise based HTTP client for the browser and node.js",
```

Not sure if it's related to how [`axios` is using the `browser` field to replace a specific file](https://github.com/axios/axios/blob/ad1195f0702381a77b4f2863aad6ddb1002ffd51/package.json#L71) or what. I can open a dedicated issue for tracking if you'd like.

**Comment by Haroenv** [comment]
I opened #130 which I think has the same origin @wKovacs64

**Comment by wKovacs64** [comment]
@haroenv Oh, cool, didn't realize that was the same thing. Thanks.

**Comment by feross** [comment]
Yes, this broke my build too. The "browser" field is being completely ignored.

**Comment by Haroenv** [comment]
This pr introduced behaviour where only the `main` file is resolved, but _all_ of the files in the browser field should be resolved as described in the map. I couldn't figure out how to make that change in this code

**Pull request merged**
