### PR TITLE
Added dedupe option to prevent bundling the same package multiple times

### PR DESCRIPTION
**Pull request by sormy**
Added dedupe option to prevent bundling the same package multiple times with unit tests

Very useful feature to make sure that specific dependency will be bundled only once and root node_modules version will be used. When npm link is used with a lot of packages it could cause specific package version to be in each package's node_modules and bundling for this scenario will cause that multiple versions of the same package will be bundled even if it is exactly the same version. Usually this is solved by defining package as peer dependency but this package could be also included in devDependencies for tests and this causes it to appear under node_modules.

### CODE REVIEW

**Comment by sormy** [comment]
The test is failing on "allows custom options" for NodeJS v6.x only.

**Comment by sormy** [comment]
I can confirm that regression for this failing test on node 6.x was introduced in commit 1eff8d75eaa914ff7ffc1663f9b34826e1c8f71d, most likely caused by `package-lock.json` update.

My change is good and don't break any tests, safe to merge.

**Comment by sormy** [comment]
Hi, any update?

**Comment by sormy** [comment]
done

**Comment by philipwalton** [comment]
Shouldn't the `dedupe` option default to deduping everything, and then you can provide exceptions if you know you want more than one version of a particular package?

As it is now, a user would have to first discover that duplication was occurring and then proactively use this option to fix it. Discovering duplication in a bundle isn't easy, so by not having it be the default, I think this will solve very few people's problems.

**Pull request merged**
