### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by mecurc**
PR included:

* drop node v6 support (EOL)
* bump version to 4.2.4
* updated dependencies
* replace buble with babel (same perfomance with no restrictions in 2019)
* start using `util.promisify`
* refactor promises with async-await (more perfomant and readable code)
* drop sync methods ( #147 )

All tests pass (thanks for tests!)

### CODE REVIEW

**Comment by mecurc** [comment]
Its PR failed with node v6 because i introduce async-await syntax that not works with node 6.

So its no matter because of node v6 dead. it's EOL = April 2019. (proof: https://github.com/nodejs/Release)

**Comment by TrySound** [comment]
I would prefer more specific PRs. "Refactoring" is too radical. Version bump will be done before publishing. Also dropping node 6 is a breaking change for those who did not updated yet. Also this project uses npm lockfile, follow it please.

**Comment by mecurc** [comment]
You're right. I will split this PR into small ones.

**Comment by lukastaegert** [comment]
Just wanted to say thanks for the huge effort you are putting into this plugin right now! Just two words from me:
- Even though Node 6 is EOL, feedback from users supports what @TrySound said. My current perspective would be to target updating the ecosystem to Node 8 maybe for next year, until then compatibility would be nice.
- Unfortunately as far as I know, this prevents both async-await and utils.promisify for the time being

**Comment by lukastaegert** [comment]
However I like the remaining changes, i.e. updating the dependencies, replacing buble with babel and replacing the sync methods!

**Pull request closed without merging**
