### PR TITLE
Support module entry point

### PR DESCRIPTION
**Pull request by TrySound**
Ref #48

### CODE REVIEW

**Comment by TrySound** [comment]
I think it should be major release.

**Comment by jdalton** [comment]
\cc @bmeck

**Comment by bmeck** [comment]
This is fine, but node has no intention to support the "module" field of package.json-schema+unsubscribe@googlegroups.com, kinda in the same bin as esnext:main

**Comment by bmeck** [comment]
Ah good old phone autocorrect,  can edit from phone, just meant the file

**Comment by bmeck** [comment]
Can't *

**Comment by taion** [comment]
Probably fine... IMO where we end up is – this stuff like tree-shaking (limited as it is) and avoiding transpiled module cruft... those concerns probably matter more for front-end anyway.

Just easier on me to not have to have both `jsnext:main` _and_ `module` just to give people slightly better front-end bundles.

**Pull request merged**
