### PR TITLE
fix(browser-resolve): fix regressions from refactor

### LINKED ISSUE #130: 3.0.1 and 3.0.2 have a regression on file size
see https://github.com/algolia/react-instantsearch/pull/831#issuecomment-356993628 and [size diff](https://bundlesize-store.now.sh/build?info=%7B%22files%22%3A%5B%7B%22maxSize%22%3A8192%2C%22path%22%3A%22packages%2Freact-instantsearch%2Fdist%2Fumd%2FCore.min.js%22%2C%22size%22%3A7494%2C%22master%22%3A7494%7D%2C%7B%22maxSize%22%3A38912%2C%22path%22%3A%22packages%2Freact-instantsearch%2Fdist%2Fumd%2FConnectors.min.js%22%2C%22size%22%3A44771%2C%22master%22%3A38225%7D%2C%7B%22maxSize%22%3A63488%2C%22path%22%3A%22packages%2Freact-instantsearch%2Fdist%2Fumd%2FDom.min.js%22%2C%22size%22%3A71426%2C%22master%22%3A62132%7D%5D%2C%22repo%22%3A%22algolia%2Freact-instantsearch%22%2C%22branch%22%3A%22renovate%2Frollup-plugin-node-resolve-3.x%22%2C%22commit_message%22%3A%22Merge%20cdedf7ac8528ef7fcda0549f2993b154d0f793c9%20into%20ef6e454b7b83cf2be793c69f5ecacc56558a509d%22%2C%22sha%22%3A%22cdedf7ac8528ef7fcda0549f2993b154d0f793c9%22%7D)

Not sure if this is enough information? 

cc @keithamus and @Rich-Harris

### PR DESCRIPTION
**Pull request by keithamus**
This should fix #130 and #131, with tests added for each regression.

### CODE REVIEW

**Comment by Andarist** [comment]
Im not entirely sure, but looking at the source code for a brief moment it seems that this PR is focused on supporting `relativeMain`, my original issue was for such package.json:
```js
{
	"main": "index.js",
	"browser": {
		"./index.js": "./browser.js",
		"./nested/dep.js": "./nested/browser-dep.js",
		"test": "./browser-test.js"
	}
}
```

And im not sure if this PR fixes that. I'd suspect `./nested/dep.js` still being resolved against wrong directory, correct me if im wrong (it would also be good to add test for my case).

We could go even further and check what gets resolved if we omit "main" entirely and leave just  "browser" field with relative paths and nested relative paths. I'd suspect at least one of those cases won't work.

**Comment by keithamus** [comment]
@Andarist this is a fix for #130 - a fix for your issue will be coming soon.

**Comment by Andarist** [comment]
Cool, haven't realized that those 2 are separate underlaying issues. 

> While I could have made a PR to browser-resolve to fix the above issues - doing so would reduce browser-resolve down to a few LOC, and I'm not sure it is under active maintainence. There are open PRs from a few years ago. I figured it would be best to move the few LOC it needs into this module.

Im only wondering if this one wouldnt be overally a better fix for the whole issue. Even if they do not merge it, ur fork could be released under a new package name - or you could even ask npm for package 'takeover' if the original package is in fact unmaintained.

Inlining this here seems like a duplicated effort - other tools could benefit from this being a separate package.

**Comment by keithamus** [comment]
@Andarist I've pushed new changes which also fix #131

**Comment by keithamus** [comment]
>  original package

I did look into this, but it added too much beurocractic complexity. Admittedly there were some regressions but the solution here is still only a handful of lines that are integrated into node-resolve. As a standalone package it would be much larger. I didn't consider it a worthwhile endeavor.

**Comment by allex** [comment]
For this issue, actually we just need provide the option `pathFilter( pkg, resvPath, relativePath );` of `resolve` module, please see #134 for detail codes..

For more about resolve module options, see:
<https://www.npmjs.com/package/resolve#resolveid-opts-cb>

**Comment by keithamus** [comment]
This has been updated to cover some additional usecases @mislav found. This should be very robust now I believe.I'm very confident in this PR.

**Comment by Rich-Harris** [comment]
released as 3.0.3, thanks!

**Pull request merged**
