### PR TITLE
es2015-in-modules support, useful for Angular (and more)

### PR DESCRIPTION
**Pull request by kylecordes**
Update dependencies so it will build/test on Node 7.

Lint cleanup

Refactor to make it easier to change the list/order of "what kind of module do you want?"

Add support for options.es2015, which is a hopefully-emerging way to say "here is es2015 code in es2015 modules". This is the format for optimal downstream tree-shaking etc with rollup and similar tools.

Useful now, to start working with Angular 4 rc.1 sitting there with es2015-code-in-es2015-modules code shipping.

### CODE REVIEW

**Comment by kylecordes** [comment]
Travis doesn't build node 0.12 anymore, but also doesn't have node 7 ready yet.

**Comment by kylecordes** [comment]
@Rich-Harris What do you think of this? Could it be merged?

**Comment by Rich-Harris** [comment]
Thanks for the PR. Is anybody doing this (`pkg.es2015`) except Angular? Am always hesitant to add something in that isn't a standard or a community convention, however small it might seem, because it can create confusion, fragmentation and technical debt. Would it make more sense for Angular to have its own dedicated resolver plugin if it's adopting idiosyncratic conventions?

**Comment by kylecordes** [comment]
There is discussion over at RxJS of shipping ES2015-in-ES2015 modules, and I suspect that if that happens they will use the same es2015 field to point to them. I have not seen any alternatives proposed for a field for this purpose, and given the benefits of ES2015-in-ES2015 modules I hope we see adoption escalate. So this perhaps a nascent community convention?

To keep the number of different plug-ins a person must find down, I thought about not adding an explicit es2015 flag, rather having the user configure an array of keys they would like searched in what order. A user could specify packageMainField: ['es2015', 'module', 'main'] or whatever other subset, combination, or order they need. I think the Webpack equivalent to rollup-plugin-node-resolve does something like this.

Downside:

* User would have to understand what those options are and in what order it is most wise to prefer them. It seems ideally best to have the tooling know the right thing and do it.

Upsides:

* As various package authors create their own new conventions, they can be met without any further edits to rollup-plugin-node-resolve.
* There is at least one other open issue about what order the fields should be searched and, in such a design would solve that one also.

I'm happy to go any of these directions though. Keep it as it is here? Publish this instead as rollup-plugin-node-resolve-es2015? Switch to the packageMainField array idea?

**Comment by TrySound** [comment]
I think we should do the same as webpack and add customizable entry points.

**Comment by Rich-Harris** [comment]
> As various package authors create their own new conventions

This is the nub of the issue — I would consider that a downside, not an upside! The thing is, I've seen how this story ends — with lots of confusion over which thing does what, and what practices should be considered 'best'. I believe that things like `es2015` should be discouraged (given that it's nowhere close to being a standard, unlike `module` which has advocates on TC39, it should *at the very least* be renamed to something that's guaranteed to never conflict with anything, like `jsnext:main` was before `module`), and 'official' plugins like this one have a role to play in setting those community conventions and expectations.

But the plugin API was designed to give this sort of freedom to people who need it, so to that end I think this would be best done as a separate Angular/RxJS-specific plugin. If it does end up being adopted more widely, it would be appropriate to revisit this.

Hope that explains my stance, and that this doesn't just come across as me being awkward! 😀

**Comment by kylecordes** [comment]
Rich - got it, the plan is to make es2015 available on a secondary plugin, and reserve this primary plugin for the NPM package features that are either already official or have wide community support.

In keeping with that, I think it's better to meet this (temporary?) pkg:es2015 need with a plugin that *can be configured* to grab pkg:es2016, rather than one that has pkg:es2015 on its feature list per se. I'm thinking of a name like rollup-plugin-node-resolve-adhoc. Or -experimental.

**Where** should such a plugin exist?

* I could publish it to NPM on my own - but then Angular people are going to keep coming here looking for es2015 support.
* I could make it then transfer the repo to you, in the rollup org, you could own and publish it to NPM.

**Comment by kylecordes** [comment]
(Actually, naming it -angular might help discoverability.)

**Comment by Rich-Harris** [comment]
Yeah, calling it something with `angular` seems like a good option. I think it's fine to have it outside the Rollup org, I don't reckon people will struggle to find it — we can include it on the [wiki](https://github.com/rollup/rollup/wiki/Plugins) etc.

**Comment by kylecordes** [comment]
I have published it, with the -angular name as @Rich-Harris recommended:

https://www.npmjs.com/package/rollup-plugin-node-resolve-angular

I linked it in the Wiki:

https://github.com/rollup/rollup/wiki/Plugins

(I'll close this PR, since things are likely to change in various chaotic ways between now and when a way of says es2015-in-es2015 is settled as official.)

**Pull request closed without merging**
