### PR TITLE
[BREAKING] Remove options.skip

### PR DESCRIPTION
**Pull request by Rich-Harris**
The `skip` option is confusing and (as far as I can tell) unnecessary. People are better off using the `external` option in the main Rollup config. Prompted by https://github.com/Rich-Harris/packd/issues/2, I'm toying with the idea of removing it. Any objections?

### CODE REVIEW

**Comment by SnareChops** [comment]
@Rich-Harris I understand the removal of this feature, unfortunately it seemed the only option that worked for our project to remove this suborn dependency from the bundles.

tl;dr; - How can I replicate the skip behaviour now that it has been removed?

The dependency is `autobahn` which is "supposed" to be compatible with browser + NodeJS, however is not rollup friendly and really nasty things happen during bundling when it is included.

The scenario is a little tricky. The frontend and backend of our application both share a common web socket connection library (internally written by us), which is awesome, however the import of autobahn causes issues for the frontend application when bundling. The `import * as autobahn from 'autobahn';` is required by the backend NodeJS application to run. We write in typescript and export straight to es5 commonjs. This works great.

In the frontend we use the same source files. So I reference the cjs output of the library in my frontend typescript + angular code. However actually importing the autobahn library is not an option in the frontend because it requires `crypto` which is a built in node module. Yes there are polyfills available for it, but the `autobahn` library actually does the right thing here and provides a browser compatible file for the browser that can be loaded globally. While global is not ideal, it works...

This was a nightmare to configure in SystemJS and unfortunately is in rollup as well. In the `rollup@^7.1.0` version I had the following which worked. `external: ['autobahn']` in the rollup options, `global: { autobahn: 'autobahn'}` in the write options, and `skip: ['autobahn']` in the node-resolve options. This finally worked and we've been running that stack for months without issue.

Full 7.1.0 config: 
```
public rollup(entryFile: string, destFile: string, minified: boolean, useStrict: boolean): Promise<void>{

		return rollup.rollup({
			entry: entryFile,
			context: 'window',
			external: ['autobahn'],
			plugins: this.getPlugins(minified)
		})
			.then((bundle: any) => {
				return bundle.write({
					format: 'iife',
					moduleName: 'oryxModule',
					sourceMap: true,
					useStrict: useStrict,
					globals: {
						autobahn: 'autobahn'
					},
					banner: `/* Auto-generated bundle created by Oryx \n * DO NOT MODIFY CODE IN THIS FILE \n * CODE WILL BE OVERWRITTEN */`,
					dest: destFile
				});
			});
	}

	private getPlugins(minified: boolean): any[]{
		const plugins: any[] = [
			bowerResolve(),
			nodeResolve({jsnext: true, module: true, browser: true, skip: ['autobahn']}),
			commonjs({
				include: 'node_modules/**',
				exclude: [
					'node_modules/autobahn/**'
				],
				namedExports: {
					'node_modules/falcor/lib/index.js': ['Model'],
					'node_modules/@angular/core/bundles/core-testing.umd.js': ['async', 'ComponentFixture', 'resetFakeAsyncZone', 'fakeAsync', 'tick', 'discardPeriodicTasks', 'flushMicrotasks', 'TestComponentRenderer', 'ComponentFixtureAutoDetect', 'ComponentFixtureNoNgZone', 'TestBed', 'getTestBed', 'inject', 'InjectSetupWrapper', 'withModule'],
					'node_modules/@angular/compiler/bundles/compiler-testing.umd.js': ['TestingCompilerFactoryImpl', 'TestingCompilerImpl', 'platformCoreDynamicTesting', 'MockSchemaRegistry', 'MockDirectiveResolver', 'MockNgModuleResolver', 'MockPipeResolver'],
					'node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic-testing.umd.js': ['platformBrowserDynamicTesting', 'BrowserDynamicTestingModule'],
					'node_modules/@angular/platform-browser/bundles/platform-browser-testing.umd.js': ['platformBrowserTesting', 'BrowserTestingModule'],
					'node_modules/@angular/router/bundles/router-testing.umd.js': ['SpyNgModuleFactoryLoader', 'setupTestingRouter', 'RouterTestingModule']
				}
			}),
			json()
		];

		if(minified){
			plugins.push(uglify());
		}
		return plugins;
	}
```

Then strikes the rxjs 5.2.0  Unexpected token issue... We downgraded the rxjs to 5.1.1 and decided to see if a patch came around. Now 5.3.0 is out and it was still not working for us, so time to upgrade rollup to the latest 8.x.x, also updating all of the dependencies. Seeing that skip is removed and also that we have `external: ['autobahn']` already set, but broken bundles, well rather the bundle succeeds, but at runtime: `Uncaught ReferenceError: module is not defined` at
```
module.exports = require('./lib/autobahn');
var index$2 = Object.freeze({});
var autobahn$1 = ( index$2 && undefined ) || index$2;
```

This wasn't an issue when skip was present. The config used when this error occurred is identical to the previous, except `skip: ['autobahn']` has been removed.

Happy to provide more information as this seems to be a small edge case, but if you know of a way to mimic the behaviour of skip so as not to include autobahn in the bundle at all (only the reference to the global) then that would be good to know.

Thanks for your time, and sorry for the extremely long post, but it is a very specific scenario. The rest of rollup has been great and "just works™" out of the box.

**Comment by jharris4** [comment]
I'm encountering a similar issue. I'm using the skip option to deal with a pesky package (typed-immutable), and I'm now also wondering about a workaround with version 3.0.0+

**Comment by jharris4** [comment]
I just created a stripped down example of using rollup to package a library that imports typed-immutable and immutable.

It currently outputs immutable.js to the bundle despite it being in the external option. Any help/suggestions on how to workaround this would be greatly appreciated.

https://github.com/jharris4/typed-immutable-rollup

**Comment by SnareChops** [comment]
@Rich-Harris Looks like this is due to #72

**Comment by BryanCrotaz** [comment]
How do you skip modules without `skip`?

Eg AWS Lambda has built in modules available (e.g. `aws-sdk`)
```
{
			entry: lambdaPath+'/index.js', 
			dest: 'index.js',
	//		format: 'cjs',
			plugins: [
				rollupResolve({
					customResolveOptions: {
						external: [
							'aws-sdk',
							'cfn-response',
							'crypto'
						]
					}
				}),
				rollupCommonjs({
					exclude: [
						'node_modules/aws-sdk/**'
					]
				}),
				rollupJson()
			]
		}
```

doesn't work

**Comment by DanielJoyce** [comment]
external is ignored currently by this plugin.

**Pull request merged**
