### PR TITLE
Allow customResolveOptions to be a function.

### PR DESCRIPTION
**Pull request by coreyfarrell**
This allows fine grained control over resolve options on a per import
basis.  For each import the function is called, allowing the user of
this module to manipulate options based on the package being imported or
the source performing the import.

### CODE REVIEW

**Comment by bennypowers** [comment]
This PR is important to my project, where indigestion in `node_modules` could bring our build system to a halt on short notice. If there's anything I can do to help move this forward, I'd be happy.

As a note to future me or anyone else this is helpful for, add this to build apollo-client and lit-element into the same bundle:

```js
const customResolveOptions = (options, id, importer) => {
  if (importer.includes('lit-')) options.basedir = __dirname; // enforce a single version of lit-*
  if (importer.includes('graphql')) options.extensions = ['.js', '.json', '.node']; // somehow, one of `graphql`'s modules uses the Michael Jackson Solution
};

/* PLUGINS */
const plugins = [
  ...beforeResolve,
  resolve({ browser: true, customResolveOptions, module: true, jsnext, preferBuiltins }),
  ...afterResolve,
];
```

**Comment by coreyfarrell** [comment]
@jirutka To be honest I've moved on.  I'm now using rollup-plugin-babel with babel-plugin-bare-import-rewrite.  I have it configured to rewrite imports using absolute filesystem path so I don't use rollup-plugin-node-resolve anymore.

I have left the PR and my git branch active because @bennypowers directly told me he was using it, but I'm really not interested in working on this any further.  I'm in no rush but eventually I'd like to delete my fork and see this PR closed.  If someone else wants to take over the final push to get this merged that would be great.

**Comment by keithamus** [comment]
If someone wants to update this PR (or make a new one off of the top of this) then I'd be happy to review it with a view to merging.

**Comment by bennypowers** [comment]
Just rebased against master. Tests pass. should work AFAICT

**Comment by bennypowers** [comment]
This should be ready to go. Any chance it'll make it in for 1.0?

**Pull request closed without merging**
